/**
 * @file Control.h
 * @brief Defines spacecraft control calculations and control commands.
 *
 * The Control module compares the spacecraft's actual state against
 * the reference state generated by Guidance and determines the
 * acceleration command required to follow that reference.
 *
 * The current implementation uses the desired acceleration directly,
 * subject to a maximum acceleration constraint. Future implementations
 * can replace or augment this behavior with feedback controllers such
 * as PID control.
 */

#ifndef CONTROL_H
#define CONTROL_H

#include "Guidance.h"
#include "State.h"
#include "Vector2D.h"

/**
 * @brief Defines constraints used by the control system.
 */
struct ControlConfig
{
    /**
     * @brief Maximum magnitude of commanded thrust acceleration.
     *
     * Units: meters per second squared (m/s^2).
     */
    double acceleration_constraint;
};

/**
 * @brief Represents tracking errors between the actual and desired state.
 *
 * Errors are calculated as:
 *
 *     position error = desired position - actual position
 *     velocity error = desired velocity - actual velocity
 */
struct TrackingError
{
    /**
     * @brief Difference between desired and actual position.
     *
     * Units: meters (m).
     */
    Vector2D position;

    /**
     * @brief Difference between desired and actual velocity.
     *
     * Units: meters per second (m/s).
     */
    Vector2D velocity;
};

/**
 * @brief Represents the acceleration command produced by the control system.
 */
struct ControlCommand
{
    /**
     * @brief Commanded thrust acceleration.
     *
     * Units: meters per second squared (m/s^2).
     */
    Vector2D thrust_acceleration;

    /**
     * @brief Duration for which the thrust command should be applied.
     *
     * Units: seconds.
     */
    double thrust_duration;
};

/**
 * @brief Calculates tracking errors between actual and desired states.
 *
 * @param current_state Actual spacecraft state.
 * @param guidance_command Desired state generated by Guidance.
 *
 * @return TrackingError containing position and velocity errors.
 */
TrackingError calculate_tracking_error(
    State current_state,
    GuidanceCommand guidance_command
);

/**
 * @brief Calculates the control command required to follow the guidance command.
 *
 * The current controller uses the desired acceleration generated by Guidance,
 * limited by the configured maximum acceleration constraint.
 *
 * @param current_state Actual spacecraft state.
 * @param guidance_command Desired trajectory state generated by Guidance.
 * @param control_config Control system configuration and constraints.
 * @param command_duration Duration for which the command should be applied.
 *
 * @return ControlCommand containing the commanded thrust acceleration
 *         and duration.
 */
ControlCommand calculate_control_command(
    State current_state,
    GuidanceCommand guidance_command,
    ControlConfig control_config,
    double command_duration
);

#endif