/**
 * @file Guidance.h
 * @brief Defines trajectory planning for the Guidance module.
 *
 * The Guidance module generates a reference trajectory for a spacecraft
 * maneuver. The current implementation uses a cubic polynomial trajectory
 * that satisfies specified initial and final position and velocity
 * boundary conditions.
 *
 * Guidance is responsible for determining where the spacecraft should be
 * and how it should be moving at a given point in the maneuver. It does
 * not determine how the spacecraft physically produces the required
 * acceleration.
 */

#ifndef GUIDANCE_H
#define GUIDANCE_H

#include "State.h"
#include "Vector2D.h"

/**
 * @brief Defines the boundary conditions for a spacecraft maneuver.
 *
 * The maneuver is specified by an initial spacecraft state, a desired
 * final spacecraft state, and the amount of time available to complete
 * the maneuver.
 */
struct ManeuverRequest
{
    /**
     * @brief Spacecraft state at the beginning of the maneuver.
     */
    State initial_state;

    /**
     * @brief Desired spacecraft state at the end of the maneuver.
     */
    State desired_state;

    /**
     * @brief Duration over which the maneuver should be completed.
     *
     * Units: seconds (s).
     */
    double maneuver_duration;
};

/**
 * @brief Coefficients defining a cubic reference trajectory.
 *
 * Each spatial component is represented independently by:
 *
 *     r(t) = r0 + v0*t + c2*t^2 + c3*t^3
 *
 * The coefficients are selected so that the trajectory satisfies the
 * specified initial and final position and velocity boundary conditions.
 */
struct TrajectoryCoefficients
{
    /**
     * @brief Quadratic trajectory coefficients for each spatial axis.
     */
    Vector2D c2;

    /**
     * @brief Cubic trajectory coefficients for each spatial axis.
     */
    Vector2D c3;
};

/**
 * @brief Contains the reference state generated by the Guidance module.
 *
 * Guidance provides the state the spacecraft should follow at the current
 * point in the maneuver.
 */
struct GuidanceCommand
{
    /**
     * @brief Reference position at the current maneuver time.
     *
     * Units: meters (m).
     */
    Vector2D desired_position;

    /**
     * @brief Reference velocity at the current maneuver time.
     *
     * Units: meters per second (m/s).
     */
    Vector2D desired_velocity;

    /**
     * @brief Reference acceleration at the current maneuver time.
     *
     * Units: meters per second squared (m/s^2).
     */
    Vector2D desired_acceleration;

    /**
     * @brief Time remaining in the maneuver.
     *
     * Units: seconds (s).
     */
    double time_remaining;
};

/**
 * @brief Calculates the position error relative to a desired position.
 *
 * The error is defined as:
 *
 *     error = desired - current
 *
 * @param current_position Current spacecraft position.
 * @param desired_position Desired or reference position.
 *
 * @return Position error vector.
 */
Vector2D calculate_position_error(
    Vector2D current_position,
    Vector2D desired_position
);

/**
 * @brief Calculates the velocity error relative to a desired velocity.
 *
 * The error is defined as:
 *
 *     error = desired - current
 *
 * @param current_velocity Current spacecraft velocity.
 * @param desired_velocity Desired or reference velocity.
 *
 * @return Velocity error vector.
 */
Vector2D calculate_velocity_error(
    Vector2D current_velocity,
    Vector2D desired_velocity
);

/**
 * @brief Calculates the coefficients of a cubic reference trajectory.
 *
 * The trajectory satisfies the four boundary conditions:
 *
 *     r(0) = initial position
 *     v(0) = initial velocity
 *     r(T) = desired position
 *     v(T) = desired velocity
 *
 * The X and Y components are solved independently.
 *
 * @param initial_state Initial spacecraft state.
 * @param desired_state Desired final spacecraft state.
 * @param maneuver_duration Duration of the maneuver.
 *
 * @return Cubic trajectory coefficients.
 */
TrajectoryCoefficients calculate_trajectory_coefficients(
    State initial_state,
    State desired_state,
    double maneuver_duration
);

/**
 * @brief Generates a guidance command at a specified maneuver time.
 *
 * Evaluates the cubic reference trajectory at the supplied elapsed time
 * and calculates the corresponding desired position, velocity, acceleration,
 * and time remaining in the maneuver.
 *
 * @param maneuver_request Maneuver boundary conditions and duration.
 * @param current_state Current simulated spacecraft state.
 * @param elapsed_time Time elapsed since the maneuver began.
 *
 * @return Guidance command containing the reference trajectory and
 *         tracking errors.
 */
GuidanceCommand calculate_guidance_command(
    ManeuverRequest maneuver_request,
    double elapsed_time
);

#endif