/**
 * @file Control.cpp
 * @brief Implements bounded control-command generation.
 *
 * The current controller applies a magnitude constraint to the desired
 * acceleration generated by Guidance.
 *
 * If the requested acceleration exceeds the configured maximum, the
 * vector is scaled without changing its direction.
 */

#include "Control.h"

#include <stdexcept>

TrackingError calculate_tracking_error(
    State current_state,
    GuidanceCommand guidance_command
)
{
    TrackingError tracking_error;

    tracking_error.position = 
        subtract_vectors(
            guidance_command.desired_position,
            current_state.position
        );

    tracking_error.velocity = 
        subtract_vectors(
            guidance_command.desired_velocity,
            current_state.velocity
        );

    return tracking_error;
}

ControlCommand calculate_control_command(
    State current_state,
    GuidanceCommand guidance_command,
    ControlConfig control_config,
    double command_duration
)
{
    /*
     * current_state is not required by the current magnitude-limiting
     * controller, but remains part of the interface for future feedback
     * control algorithms such as PID control.
     */
    (void)current_state;

    if (control_config.acceleration_constraint <= 0.0)
    {
        throw std::runtime_error(
            "Maximum acceleration must be greater than zero."
        );
    }

    if (command_duration < 0.0)
    {
        throw std::runtime_error(
            "Command duration cannot be negative."
        );
    }

    Vector2D desired_acceleration =
        guidance_command.desired_acceleration;

    double desired_magnitude =
        calculate_magnitude(
            desired_acceleration
        );

    ControlCommand control_command;

    /*
     * No requested acceleration means no thrust command.
     */
    if (desired_magnitude == 0.0)
    {
        control_command.thrust_acceleration = {
            0.0,
            0.0
        };

        control_command.thrust_duration = 0.0;

        return control_command;
    }

    /*
     * If the requested acceleration is within the vehicle's
     * constraint, it can be applied directly.
     */
    if (desired_magnitude <=
        control_config.acceleration_constraint)
    {
        control_command.thrust_acceleration =
            desired_acceleration;
    }
    else
    {
        /*
         * Preserve direction while limiting magnitude:
         *
         *     a_command =
         *         a_desired *
         *         (a_max / |a_desired|)
         */
        control_command.thrust_acceleration =
            scale_vector(
                desired_acceleration,
                control_config.acceleration_constraint /
                desired_magnitude
            );
    }

    control_command.thrust_duration =
        command_duration;

    return control_command;
}